# frozen_string_literal: true

source 'https://rubygems.org'

gem 'actionpack', '~> 8.1'
gem 'activerecord', '~> 8.1'
gem 'bcrypt', '~> 3.1'
gem 'dynamic-active-model-rails', '~> 1.3', '>= 1.3.2'
gem 'puma'
gem 'railties', '~> 8.1'
gem 'schema-api', path: '../..'
gem 'sqlite3', '>= 2.1'

group :development, :test do
  gem 'rspec-rails'
end
