# frozen_string_literal: true

source 'https://rubygems.org'

gem 'actionpack', '~> 8.1'
gem 'activerecord', '~> 8.1'
gem 'bcrypt', '~> 3.1'
gem 'dynamic-active-model-rails', '~> 1.3'
gem 'puma'
gem 'railties', '~> 8.1'
gem 'schema-api', path: '../..'
# unreleased schema-model changes schema-api relies on; see ../../Gemfile
gem 'schema-model', git: 'https://github.com/dougyouch/schema.git', branch: 'feat/schema-api-support'
gem 'sqlite3', '>= 2.1'

group :development, :test do
  gem 'rspec-rails'
end
